### ISSUE TITLE
Uplift Kamon version from 1.1.6 to 2.1.1

### ISSUE THREAD

**Issue by peter-hazell** [sky-uk/kafka-message-scheduler#100]
### Background

We have seen the following error when memory usage is high:

```
fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe (Write failed) at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socket
```

According to previous investigations into the same error, this is because KMS Kamon is closing the connection with prometheus, resulting in errors and lost metrics.

We believe the above is due to the app using too much memory, effectively slowing it down causing the connection to prometheus to close.

https://github.com/kamon-io/Kamon/issues/754 mentions the error and [2.1.1](https://github.com/kamon-io/Kamon/releases/tag/v2.1.1) of kamon removes NanoHTTP (kms is on [1.1.6](https://github.com/sky-uk/kafka-message-scheduler/blob/e438811bdccb63f922dadd1d76cca7a74ad89df8/build.sbt#L32))

### Acceptance Criteria

- Uplift Kamon version from 1.1.6 to 2.1.1 which removes NanoHTTP, which should stop errors when prometheus is scraping the app

**Comment by bcarter97** [comment]
Issue has been fixed, see https://github.com/sky-uk/kafka-message-scheduler/pull/101#issue-593013589 for notes
