### ISSUE TITLE
Sky (NOWTV) channels security issue

### ISSUE THREAD

**Issue by stop-piracy** [sky-uk/kafka-message-scheduler#199]
Hey,

I am trying to reach any dev working here to report this:
https://gist.github.com/stop-piracy/d816e7a342d41544ae07ac339803e21d

**Comment by ThunderHawkCode** [comment]
@paoloambrosio-skyuk Sky doesn't care?
Was this the slogan? https://twitter.com/seriea_en/status/1558431706910265345
