### ISSUE TITLE
GitLeaks - HashiCorp Terraform password field

### ISSUE THREAD

**Issue by SkyDevSecOps-SCMA** [sky-uk/kafka-message-scheduler#315]
Locations:<br><ul><li><a href='https://github.com/sky-uk/kafka-message-scheduler/blob/80f33c6f7e72d055a52c1dad74ee01bf3f575673/scheduler/src/main/resources/application.conf#L38-L38'>scheduler/src/main/resources/application.conf</a></li><li><a href='https://github.com/sky-uk/kafka-message-scheduler/blob/80f33c6f7e72d055a52c1dad74ee01bf3f575673/scheduler/src/main/resources/application.conf#L42-L42'>scheduler/src/main/resources/application.conf</a></li><li><a href='https://github.com/sky-uk/kafka-message-scheduler/blob/80f33c6f7e72d055a52c1dad74ee01bf3f575673/scheduler/src/main/resources/application.conf#L62-L62'>scheduler/src/main/resources/application.conf</a></li><li><a href='https://github.com/sky-uk/kafka-message-scheduler/blob/80f33c6f7e72d055a52c1dad74ee01bf3f575673/scheduler/src/main/resources/application.conf#L66-L66'>scheduler/src/main/resources/application.conf</a></li></ul><br> In case of questions please visit our FAQ page here: https://skyglobal.sharepoint.com/sites/GroupCyberSecurity10/SitePages/Software-Security.aspx

**Comment by paoloambrosio-skyuk** [comment]
The branch containing this external contribution has been removed. It was not a security risk as the `password` seemed to unlock a dev keystore in the user's machine.
